services:
  - type: web
    name: questionnaires-mapp
    env: python
    buildCommand: "./setup.sh"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "True"
      - key: PORT
        value: "10000"
    includePaths:
      - "app.py"
      - "requirements.txt"
      - "setup.sh"
      - "data/**"
      - "script/**"
    ignorePaths:
      - "README.md"
      - "BACKUP_README.md"
      - "*.md"
      - ".gitignore"
      - "fiches_backup.zip"
